
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Session: 'Session',
  Node: 'Node',
  Edge: 'Edge',
  DashboardStat: 'DashboardStat',
  GridConfig: 'GridConfig'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  hashedPassword: 'hashedPassword',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const NodeScalarFieldEnum = {
  id: 'id',
  label: 'label',
  designation: 'designation',
  category: 'category',
  status: 'status',
  websiteUrl: 'websiteUrl',
  capacityData: 'capacityData',
  nodeColor: 'nodeColor',
  textColor: 'textColor',
  x: 'x',
  y: 'y',
  manualX: 'manualX',
  manualY: 'manualY',
  useManualOverride: 'useManualOverride',
  parentId: 'parentId',
  icon: 'icon',
  kpiValue: 'kpiValue',
  kpiUnit: 'kpiUnit',
  lastUpdated: 'lastUpdated',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NodeScalarFieldEnum = (typeof NodeScalarFieldEnum)[keyof typeof NodeScalarFieldEnum]


export const EdgeScalarFieldEnum = {
  id: 'id',
  sourceId: 'sourceId',
  targetId: 'targetId',
  edgeColor: 'edgeColor',
  edgeStyle: 'edgeStyle',
  label: 'label',
  flowVolume: 'flowVolume',
  flowType: 'flowType',
  animated: 'animated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EdgeScalarFieldEnum = (typeof EdgeScalarFieldEnum)[keyof typeof EdgeScalarFieldEnum]


export const DashboardStatScalarFieldEnum = {
  id: 'id',
  statName: 'statName',
  value: 'value',
  calculatedValue: 'calculatedValue',
  isManualOverride: 'isManualOverride',
  unit: 'unit',
  formula: 'formula',
  lastCalculated: 'lastCalculated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DashboardStatScalarFieldEnum = (typeof DashboardStatScalarFieldEnum)[keyof typeof DashboardStatScalarFieldEnum]


export const GridConfigScalarFieldEnum = {
  id: 'id',
  canvasWidth: 'canvasWidth',
  canvasHeight: 'canvasHeight',
  gridSize: 'gridSize',
  nodeWidth: 'nodeWidth',
  nodeHeight: 'nodeHeight',
  horizontalSpacing: 'horizontalSpacing',
  verticalSpacing: 'verticalSpacing',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GridConfigScalarFieldEnum = (typeof GridConfigScalarFieldEnum)[keyof typeof GridConfigScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

