import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database with Bangladesh Power Sector data...')

  await prisma.edge.deleteMany()
  await prisma.node.deleteMany()
  await prisma.user.deleteMany()
  await prisma.dashboardStat.deleteMany()
  await prisma.gridConfig.deleteMany()

  const hashedPassword = await bcrypt.hash('admin123', 10)
  const adminUser = await prisma.user.create({
    data: {
      email: 'admin@power.gov.bd',
      hashedPassword,
      name: 'System Administrator',
    },
  })
  console.log('✅ Created admin user:', adminUser.email)

  const nodes = [
    {
      id: 'mpemr',
      label: 'Ministry of Power, Energy & Mineral Resources',
      designation: 'Ministry',
      category: 'government',
      status: 'normal',
      nodeColor: '#64748b',
      websiteUrl: 'https://power.gov.bd',
      capacityData: '1',
      icon: 'building',
      kpiValue: '1',
      kpiUnit: 'Ministry',
      lastUpdated: new Date().toISOString(),
      description: 'The supreme policy-making body overseeing the entire energy and mineral resources sector, ensuring national energy security and sustainable growth.',
    },
    {
      id: 'powerDiv',
      label: 'Power Division',
      designation: 'Division',
      category: 'government',
      parentId: 'mpemr',
      status: 'normal',
      nodeColor: '#64748b',
      websiteUrl: 'https://power.gov.bd/site/page/2e5cfb43-4d91-462d-b5cd-48caa3e6e08a',
      capacityData: '11000',
      icon: 'trending',
      kpiValue: '11000',
      kpiUnit: 'MW Supervised',
      lastUpdated: new Date().toISOString(),
      description: 'Responsible for the holistic management, strategic planning, and regulatory oversight of electricity generation, transmission, and distribution across the nation.',
    },
    {
      id: 'energyDiv',
      label: 'Energy and Mineral Resources Division',
      designation: 'Division',
      category: 'government',
      parentId: 'mpemr',
      status: 'normal',
      nodeColor: '#64748b',
      websiteUrl: 'https://energy.gov.bd',
      capacityData: '1200',
      icon: 'zap',
      kpiValue: '1200',
      kpiUnit: 'MW Supervised',
      lastUpdated: new Date().toISOString(),
      description: 'Coordinates the exploration, production, and import of primary fuels (gas, coal, oil) and spearheads renewable energy policy implementation.',
    },
    {
      id: 'berc',
      label: 'Bangladesh Energy Regulatory Commission',
      designation: 'Independent Regulator',
      category: 'regulator',
      status: 'normal',
      nodeColor: '#059669',
      websiteUrl: 'https://berc.org.bd',
      capacityData: '47',
      icon: 'cpu',
      kpiValue: '47',
      kpiUnit: 'Tariff Changes/Year',
      lastUpdated: new Date().toISOString(),
      description: 'An independent statutory body that ensures fair tariffs, promotes competition, and protects consumer rights in the electricity and downstream gas sectors.',
    },
    {
      id: 'bpdb',
      label: 'BPDB (Bangladesh Power Development Board)',
      designation: 'Generation Company',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      websiteUrl: 'https://www.bpdb.gov.bd',
      capacityData: '6600',
      icon: 'factory',
      kpiValue: '6600',
      kpiUnit: 'MW Capacity',
      lastUpdated: new Date().toISOString(),
      description: 'The largest state-owned statutory body functioning as the single buyer of electricity and managing massive public generation facilities.',
    },
    {
      id: 'bpdb-coal',
      label: 'BPDB Coal Plants',
      designation: 'Generation Sub-unit',
      category: 'generation',
      parentId: 'bpdb',
      status: 'normal',
      nodeColor: '#0D9488',
      capacityData: '2800',
      icon: 'factory',
      kpiValue: '2800',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'Major baseload thermal power stations utilizing domestic and imported coal to maintain grid stability and meet base demand.',
    },
    {
      id: 'bpdb-gas',
      label: 'BPDB Gas Plants',
      designation: 'Generation Sub-unit',
      category: 'generation',
      parentId: 'bpdb',
      status: 'warning',
      nodeColor: '#0D9488',
      capacityData: '3200',
      icon: 'factory',
      kpiValue: '3200',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'The backbone of the power grid, these stations use domestic natural gas and imported LNG to provide reliable and cost-effective electricity.',
    },
    {
      id: 'bpdb-hydro',
      label: 'BPDB Hydro Plants',
      designation: 'Generation Sub-unit',
      category: 'generation',
      parentId: 'bpdb',
      status: 'normal',
      nodeColor: '#0D9488',
      capacityData: '230',
      icon: 'droplet',
      kpiValue: '230',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'Eco-friendly renewable energy facilities harnessing water flow to provide essential peaking power and grid frequency regulation.',
    },
    {
      id: 'bpdb-renewable',
      label: 'BPDB Solar & Wind',
      designation: 'Generation Sub-unit',
      category: 'generation',
      parentId: 'bpdb',
      status: 'normal',
      nodeColor: '#0D9488',
      capacityData: '370',
      icon: 'leaf',
      kpiValue: '370',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'Key sustainability projects integrating utility-scale solar parks and coastal wind farms to reduce carbon footprint and fossil fuel dependency.',
    },
    {
      id: 'summit-power',
      label: 'Summit Power',
      designation: 'IPP',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      websiteUrl: 'https://summitpower.net',
      capacityData: '1500',
      icon: 'factory',
      kpiValue: '1500',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'A leading Independent Power Producer (IPP) contributing significantly to the national grid through high-efficiency combined cycle power plants.',
    },
    {
      id: 'united-power',
      label: 'United Power',
      designation: 'IPP',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      websiteUrl: 'https://unitedpower.net',
      capacityData: '1200',
      icon: 'factory',
      kpiValue: '1200',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'Major private power producer',
    },
    {
      id: 'confidence-power',
      label: 'Confidence Power',
      designation: 'IPP',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      websiteUrl: 'https://confidencepower.net',
      capacityData: '600',
      icon: 'factory',
      kpiValue: '600',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'Major private power producer',
    },
    {
      id: 'other-ipps',
      label: 'Other IPPs & Private Generators',
      designation: 'IPP Group',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      capacityData: '2100',
      icon: 'factory',
      kpiValue: '2100',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'A diverse portfolio of private sector generation companies adding critical capacity and fostering market competition.',
    },
    {
      id: 'rental-power',
      label: 'Rental Power Plants',
      designation: 'Emergency Generation',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'warning',
      nodeColor: '#0D9488',
      capacityData: '800',
      icon: 'factory',
      kpiValue: '800',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'Quick-rental and rental power plants deployed to rapidly address short-term power deficits and stabilize regional supply.',
    },
    {
      id: 'adani-godda',
      label: 'Adani Godda (India Import)',
      designation: 'Import',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      capacityData: '500',
      icon: 'trending',
      kpiValue: '500',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'A dedicated cross-border transmission link importing baseload coal power from the Adani Godda plant in India.',
    },
    {
      id: 'tripura-import',
      label: 'Tripura Import (India)',
      designation: 'Import',
      category: 'generation',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#0D9488',
      capacityData: '300',
      icon: 'trending',
      kpiValue: '300',
      kpiUnit: 'MW',
      lastUpdated: new Date().toISOString(),
      description: 'A strategic cross-border interconnection importing clean hydroelectric power from Tripura, India, strengthening regional cooperation.',
    },
    {
      id: 'petrobangla',
      label: 'Petrobangla',
      designation: 'Fuel Supplier',
      category: 'fuel',
      parentId: 'energyDiv',
      status: 'warning',
      nodeColor: '#DC2626',
      websiteUrl: 'https://petrobangla.gov.bd',
      capacityData: '1850',
      icon: 'droplet',
      kpiValue: '1850',
      kpiUnit: 'MMcfd Gas',
      lastUpdated: new Date().toISOString(),
      description: 'The national oil company responsible for exploration, production, and distribution of natural gas and mineral resources.',
    },
    {
      id: 'rpgcl',
      label: 'RPGCL (LNG Terminal)',
      designation: 'Fuel Supplier',
      category: 'fuel',
      parentId: 'energyDiv',
      status: 'normal',
      nodeColor: '#DC2626',
      websiteUrl: 'https://rpgcl.gov.bd',
      capacityData: '5.5',
      icon: 'droplet',
      kpiValue: '5.5',
      kpiUnit: 'MMTPA',
      lastUpdated: new Date().toISOString(),
      description: 'Manages the importation, regasification, and integration of LNG to supplement declining domestic natural gas reserves.',
    },
    {
      id: 'coal-suppliers',
      label: 'Coal Suppliers',
      designation: 'Fuel Supplier',
      category: 'fuel',
      parentId: 'energyDiv',
      status: 'normal',
      nodeColor: '#DC2626',
      capacityData: '18',
      icon: 'trending',
      kpiValue: '18',
      kpiUnit: 'Million Tonnes/Year',
      lastUpdated: new Date().toISOString(),
      description: 'International supply chains ensuring the delivery of high-calorific-value coal for major baseload power plants.',
    },
    {
      id: 'renewable-fuel',
      label: 'Renewable Energy Sources',
      designation: 'Fuel Supplier',
      category: 'fuel',
      parentId: 'energyDiv',
      status: 'normal',
      nodeColor: '#DC2626',
      capacityData: '1500',
      icon: 'leaf',
      kpiValue: '1500',
      kpiUnit: 'MW Target',
      lastUpdated: new Date().toISOString(),
      description: 'A growing sector of decentralized and grid-tied renewable resources aiming to diversify the primary energy mix.',
    },
    {
      id: 'pgcb',
      label: 'PGCB (National Grid)',
      designation: 'Transmission Company',
      category: 'transmission',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#1E3A8A',
      websiteUrl: 'https://pgcb.net.bd',
      capacityData: '24000',
      icon: 'network',
      kpiValue: '24000',
      kpiUnit: 'Circuit KM',
      lastUpdated: new Date().toISOString(),
      description: 'The sole state-owned entity responsible for operating, maintaining, and expanding the national high-voltage transmission grid.',
    },
    {
      id: 'nldc',
      label: 'NLDC (National Load Despatch Centre)',
      designation: 'Grid Operations',
      category: 'transmission',
      parentId: 'pgcb',
      status: 'normal',
      nodeColor: '#1E3A8A',
      websiteUrl: 'https://pgcb.net.bd/site/page/nldc',
      capacityData: '14000',
      icon: 'cpu',
      kpiValue: '14000',
      kpiUnit: 'MW Real-time',
      lastUpdated: new Date().toISOString(),
      description: 'The central nervous system of the grid, balancing real-time supply and demand, and maintaining system frequency within safe limits.',
    },
    {
      id: 'dpdc',
      label: 'DPDC (Dhaka South Distribution)',
      designation: 'Distribution Company',
      category: 'distribution',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#D97706',
      websiteUrl: 'https://dpdc.org.bd',
      capacityData: '3200',
      icon: 'network',
      kpiValue: '3200',
      kpiUnit: 'MW Peak',
      lastUpdated: new Date().toISOString(),
      description: 'Manages the intricate power distribution network for the southern parts of the capital and adjacent highly industrialized areas.',
    },
    {
      id: 'desco',
      label: 'DESCO (Dhaka North Distribution)',
      designation: 'Distribution Company',
      category: 'distribution',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#D97706',
      websiteUrl: 'https://desco.org.bd',
      capacityData: '2800',
      icon: 'network',
      kpiValue: '2800',
      kpiUnit: 'MW Peak',
      lastUpdated: new Date().toISOString(),
      description: 'Delivers reliable electricity to the northern half of the capital, encompassing major commercial hubs and residential zones.',
    },
    {
      id: 'breb',
      label: 'BREB (Rural Electrification Board)',
      designation: 'Distribution Company',
      category: 'distribution',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#D97706',
      websiteUrl: 'https://breb.gov.bd',
      capacityData: '1500',
      icon: 'network',
      kpiValue: '1500',
      kpiUnit: 'MW Peak',
      lastUpdated: new Date().toISOString(),
      description: 'The largest distribution network in the country, electrifying thousands of villages through rural cooperatives.',
    },
    {
      id: 'nesco',
      label: 'NESCO (North Distribution)',
      designation: 'Distribution Company',
      category: 'distribution',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#D97706',
      websiteUrl: 'https://nesco.org.bd',
      capacityData: '1200',
      icon: 'network',
      kpiValue: '1200',
      kpiUnit: 'MW Peak',
      lastUpdated: new Date().toISOString(),
      description: 'Ensures stable power supply to the Rajshahi and Rangpur divisions, supporting regional agricultural and industrial growth.',
    },
    {
      id: 'wzpdc',
      label: 'WZPDC (West/South Distribution)',
      designation: 'Distribution Company',
      category: 'distribution',
      parentId: 'powerDiv',
      status: 'normal',
      nodeColor: '#D97706',
      websiteUrl: 'https://wzpdc.org.bd',
      capacityData: '1100',
      icon: 'network',
      kpiValue: '1100',
      kpiUnit: 'MW Peak',
      lastUpdated: new Date().toISOString(),
      description: 'Provides electricity to the Khulna and Barisal divisions, encompassing major ports and coastal economic zones.',
    },
    {
      id: 'industrial-consumer',
      label: 'Industrial Consumers',
      designation: 'Consumer Segment',
      category: 'consumer',
      parentId: 'nldc',
      status: 'normal',
      nodeColor: '#7C3AED',
      capacityData: '4800',
      icon: 'factory',
      kpiValue: '4800',
      kpiUnit: 'MW Demand',
      lastUpdated: new Date().toISOString(),
      description: 'High-demand industrial hubs driving the national economy, requiring uninterrupted and high-quality power supply.',
    },
    {
      id: 'commercial-consumer',
      label: 'Commercial Consumers',
      designation: 'Consumer Segment',
      category: 'consumer',
      parentId: 'nldc',
      status: 'normal',
      nodeColor: '#7C3AED',
      capacityData: '2400',
      icon: 'building',
      kpiValue: '2400',
      kpiUnit: 'MW Demand',
      lastUpdated: new Date().toISOString(),
      description: 'The urban commercial backbone, characterized by fluctuating daytime demand driven by commercial complexes and essential services.',
    },
    {
      id: 'agricultural-consumer',
      label: 'Agricultural Consumers',
      designation: 'Consumer Segment',
      category: 'consumer',
      parentId: 'nldc',
      status: 'normal',
      nodeColor: '#7C3AED',
      capacityData: '1800',
      icon: 'leaf',
      kpiValue: '1800',
      kpiUnit: 'MW Demand',
      lastUpdated: new Date().toISOString(),
      description: 'Critical seasonal load driven by rural irrigation pumps ensuring national food security and agricultural productivity.',
    },
    {
      id: 'residential-consumer',
      label: 'Residential Consumers',
      designation: 'Consumer Segment',
      category: 'consumer',
      parentId: 'nldc',
      status: 'normal',
      nodeColor: '#7C3AED',
      capacityData: '5600',
      icon: 'users',
      kpiValue: '5600',
      kpiUnit: 'MW Demand',
      lastUpdated: new Date().toISOString(),
      description: 'The largest consumer base by volume, representing millions of households with a predominantly evening peak demand profile.',
    },
  ]

  const createdNodes = [];
  for (const node of nodes) {
    createdNodes.push(await prisma.node.create({ data: node }));
  }

  console.log(`✅ Created ${createdNodes.length} nodes`)

  const edges = [
    { sourceId: 'mpemr', targetId: 'powerDiv' },
    { sourceId: 'mpemr', targetId: 'energyDiv' },
    { sourceId: 'mpemr', targetId: 'berc' },
    { sourceId: 'powerDiv', targetId: 'bpdb' },
    { sourceId: 'powerDiv', targetId: 'pgcb' },
    { sourceId: 'powerDiv', targetId: 'dpdc' },
    { sourceId: 'bpdb', targetId: 'bpdb-coal' },
    { sourceId: 'bpdb', targetId: 'bpdb-gas' },
    { sourceId: 'bpdb', targetId: 'bpdb-hydro' },
    { sourceId: 'bpdb', targetId: 'bpdb-renewable' },
    { sourceId: 'bpdb-coal', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '2,800 MW' },
    { sourceId: 'bpdb-gas', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '3,200 MW' },
    { sourceId: 'bpdb-hydro', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '230 MW' },
    { sourceId: 'bpdb-renewable', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '370 MW' },
    { sourceId: 'summit-power', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '1,500 MW' },
    { sourceId: 'united-power', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '1,200 MW' },
    { sourceId: 'confidence-power', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '600 MW' },
    { sourceId: 'other-ipps', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '2,100 MW' },
    { sourceId: 'rental-power', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '800 MW' },
    { sourceId: 'adani-godda', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '500 MW' },
    { sourceId: 'tripura-import', targetId: 'pgcb', edgeColor: '#475569', animated: true, label: '300 MW' },
    { sourceId: 'petrobangla', targetId: 'bpdb-gas', edgeColor: '#DC2626', label: '1,850 MMcfd' },
    { sourceId: 'rpgcl', targetId: 'bpdb-gas', edgeColor: '#DC2626', label: '5.5 MMTPA' },
    { sourceId: 'coal-suppliers', targetId: 'bpdb-coal', edgeColor: '#DC2626', label: '18 MT/Year' },
    { sourceId: 'renewable-fuel', targetId: 'bpdb-renewable', edgeColor: '#DC2626', label: 'Solar/Wind' },
    { sourceId: 'pgcb', targetId: 'nldc' },
    { sourceId: 'nldc', targetId: 'dpdc' },
    { sourceId: 'nldc', targetId: 'desco' },
    { sourceId: 'nldc', targetId: 'breb' },
    { sourceId: 'nldc', targetId: 'nesco' },
    { sourceId: 'nldc', targetId: 'wzpdc' },
    { sourceId: 'dpdc', targetId: 'industrial-consumer', edgeColor: '#475569', label: '1,600 MW' },
    { sourceId: 'dpdc', targetId: 'commercial-consumer', edgeColor: '#475569', label: '800 MW' },
    { sourceId: 'dpdc', targetId: 'residential-consumer', edgeColor: '#475569', label: '1,800 MW' },
    { sourceId: 'desco', targetId: 'industrial-consumer', edgeColor: '#475569', label: '1,200 MW' },
    { sourceId: 'desco', targetId: 'residential-consumer', edgeColor: '#475569', label: '1,600 MW' },
    { sourceId: 'breb', targetId: 'agricultural-consumer', edgeColor: '#475569', label: '1,200 MW' },
    { sourceId: 'breb', targetId: 'residential-consumer', edgeColor: '#475569', label: '800 MW' },
    { sourceId: 'nesco', targetId: 'industrial-consumer', edgeColor: '#475569', label: '800 MW' },
    { sourceId: 'nesco', targetId: 'commercial-consumer', edgeColor: '#475569', label: '400 MW' },
    { sourceId: 'wzpdc', targetId: 'commercial-consumer', edgeColor: '#475569', label: '200 MW' },
    { sourceId: 'wzpdc', targetId: 'industrial-consumer', edgeColor: '#475569', label: '200 MW' },
    { sourceId: 'wzpdc', targetId: 'residential-consumer', edgeColor: '#475569', label: '400 MW' },
    { sourceId: 'berc', targetId: 'bpdb' },
    { sourceId: 'berc', targetId: 'dpdc' },
    { sourceId: 'berc', targetId: 'desco' },
  ]

  const createdEdges = await Promise.all(
    edges.map((edge) =>
      prisma.edge.create({
        data: edge,
      })
    )
  )
  console.log(`✅ Created ${createdEdges.length} edges`)

  const stats = [
    {
      statName: 'Total Generation Capacity',
      value: 22700,
      calculatedValue: 22700,
      unit: 'MW',
      formula: 'Sum of all generation nodes capacity',
    },
    {
      statName: 'System Efficiency',
      value: 87.5,
      calculatedValue: 87.5,
      unit: '%',
      formula: 'Load factor calculation from distribution',
    },
    {
      statName: 'Total Distribution Capacity',
      value: 9800,
      calculatedValue: 9800,
      unit: 'MW',
      formula: 'Sum of all distribution companies peak demand',
    },
    {
      statName: 'Peak Demand',
      value: 14800,
      calculatedValue: 14800,
      unit: 'MW',
      formula: 'Sum of all consumer segments',
    },
    {
      statName: 'Renewable Energy',
      value: 370,
      calculatedValue: 370,
      unit: 'MW',
      formula: 'Sum of solar and wind capacity',
    },
  ]

  const createdStats = await Promise.all(
    stats.map((stat) =>
      prisma.dashboardStat.create({
        data: stat,
      })
    )
  )
  console.log(`✅ Created ${createdStats.length} dashboard stats`)

  const gridConfig = await prisma.gridConfig.create({
    data: {
      canvasWidth: 1920,
      canvasHeight: 1080,
      gridSize: 100,
      nodeWidth: 280,
      nodeHeight: 140,
      horizontalSpacing: 320,
      verticalSpacing: 180,
    },
  })
  console.log('✅ Created grid configuration')

  console.log('🎉 Database seeding completed!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
