/**
 * Seed Script - Populates Bangladesh Power Sector data via API
 * Usage: Run after the app is started with `npm run dev`
 * Then in another terminal: npx tsx scripts/seed-api.ts
 */

const BASE_URL = 'http://localhost:3000'

interface NodeData {
  id: string
  label: string
  designation: string
  category: string
  status: string
  nodeColor: string
  websiteUrl?: string
  capacityData?: string
  icon?: string
  kpiValue?: string
  kpiUnit?: string
  description?: string
}

const nodes: NodeData[] = [
  {
    id: 'mpemr',
    label: 'Ministry of Power, Energy & Mineral Resources',
    designation: 'Ministry',
    category: 'government',
    status: 'normal',
    nodeColor: '#64748b',
    websiteUrl: 'https://power.gov.bd',
    capacityData: '1',
    icon: 'building',
    kpiValue: '1',
    kpiUnit: 'Ministry',
    description: 'National policy oversight for energy sector',
  },
  {
    id: 'powerDiv',
    label: 'Power Division',
    designation: 'Division',
    category: 'government',
    status: 'normal',
    nodeColor: '#64748b',
    websiteUrl: 'https://power.gov.bd/site/page/2e5cfb43-4d91-462d-b5cd-48caa3e6e08a',
    capacityData: '11000',
    icon: 'trending',
    kpiValue: '11000',
    kpiUnit: 'MW Supervised',
    description: 'Oversees generation, transmission, and distribution',
  },
  {
    id: 'energyDiv',
    label: 'Energy and Mineral Resources Division',
    designation: 'Division',
    category: 'government',
    status: 'normal',
    nodeColor: '#64748b',
    websiteUrl: 'https://energy.gov.bd',
    capacityData: '1200',
    icon: 'zap',
    kpiValue: '1200',
    kpiUnit: 'MW Supervised',
    description: 'Renewable energy and fuel import coordination',
  },
  {
    id: 'berc',
    label: 'Bangladesh Energy Regulatory Commission',
    designation: 'Independent Regulator',
    category: 'regulator',
    status: 'normal',
    nodeColor: '#059669',
    websiteUrl: 'https://berc.org.bd',
    capacityData: '47',
    icon: 'cpu',
    kpiValue: '47',
    kpiUnit: 'Tariff Changes/Year',
    description: 'Independent electricity and gas regulator',
  },
  {
    id: 'bpdb',
    label: 'BPDB (Bangladesh Power Development Board)',
    designation: 'Generation Company',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    websiteUrl: 'https://www.bpdb.gov.bd',
    capacityData: '6600',
    icon: 'factory',
    kpiValue: '6600',
    kpiUnit: 'MW Capacity',
    description: 'State-owned generation utility',
  },
  {
    id: 'bpdb-coal',
    label: 'BPDB Coal Plants',
    designation: 'Generation Sub-unit',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    capacityData: '2800',
    icon: 'factory',
    kpiValue: '2800',
    kpiUnit: 'MW',
    description: 'Barapukuria, Rangpur coal facilities',
  },
  {
    id: 'bpdb-gas',
    label: 'BPDB Gas Plants',
    designation: 'Generation Sub-unit',
    category: 'generation',
    status: 'warning',
    nodeColor: '#0D9488',
    capacityData: '3200',
    icon: 'factory',
    kpiValue: '3200',
    kpiUnit: 'MW',
    description: 'Natural gas powered generating stations',
  },
  {
    id: 'bpdb-hydro',
    label: 'BPDB Hydro Plants',
    designation: 'Generation Sub-unit',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    capacityData: '230',
    icon: 'droplet',
    kpiValue: '230',
    kpiUnit: 'MW',
    description: 'Kaptai and Teesta hydroelectric facilities',
  },
  {
    id: 'bpdb-renewable',
    label: 'BPDB Solar & Wind',
    designation: 'Generation Sub-unit',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    capacityData: '370',
    icon: 'leaf',
    kpiValue: '370',
    kpiUnit: 'MW',
    description: 'Solar and wind energy initiatives',
  },
  {
    id: 'summit-power',
    label: 'Summit Power',
    designation: 'IPP',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    websiteUrl: 'https://summitpower.net',
    capacityData: '1500',
    icon: 'factory',
    kpiValue: '1500',
    kpiUnit: 'MW',
    description: 'Major private power producer',
  },
  {
    id: 'united-power',
    label: 'United Power',
    designation: 'IPP',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    websiteUrl: 'https://unitedpower.net',
    capacityData: '1200',
    icon: 'factory',
    kpiValue: '1200',
    kpiUnit: 'MW',
    description: 'Major private power producer',
  },
  {
    id: 'confidence-power',
    label: 'Confidence Power',
    designation: 'IPP',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    websiteUrl: 'https://confidencepower.net',
    capacityData: '600',
    icon: 'factory',
    kpiValue: '600',
    kpiUnit: 'MW',
    description: 'Major private power producer',
  },
  {
    id: 'other-ipps',
    label: 'Other IPPs & Private Generators',
    designation: 'IPP Group',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    capacityData: '2100',
    icon: 'factory',
    kpiValue: '2100',
    kpiUnit: 'MW',
    description: 'Various smaller independent producers',
  },
  {
    id: 'rental-power',
    label: 'Rental Power Plants',
    designation: 'Emergency Generation',
    category: 'generation',
    status: 'warning',
    nodeColor: '#0D9488',
    capacityData: '800',
    icon: 'factory',
    kpiValue: '800',
    kpiUnit: 'MW',
    description: 'Short-term emergency power capacity',
  },
  {
    id: 'adani-godda',
    label: 'Adani Godda (India Import)',
    designation: 'Import',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    capacityData: '500',
    icon: 'trending',
    kpiValue: '500',
    kpiUnit: 'MW',
    description: 'Coal-based import from India',
  },
  {
    id: 'tripura-import',
    label: 'Tripura Import (India)',
    designation: 'Import',
    category: 'generation',
    status: 'normal',
    nodeColor: '#0D9488',
    capacityData: '300',
    icon: 'trending',
    kpiValue: '300',
    kpiUnit: 'MW',
    description: 'Hydro power import from Tripura',
  },
  {
    id: 'petrobangla',
    label: 'Petrobangla',
    designation: 'Fuel Supplier',
    category: 'fuel',
    status: 'warning',
    nodeColor: '#DC2626',
    websiteUrl: 'https://petrobangla.gov.bd',
    capacityData: '1850',
    icon: 'droplet',
    kpiValue: '1850',
    kpiUnit: 'MMcfd Gas',
    description: 'State-owned gas supplier and producer',
  },
  {
    id: 'rpgcl',
    label: 'RPGCL (LNG Terminal)',
    designation: 'Fuel Supplier',
    category: 'fuel',
    status: 'normal',
    nodeColor: '#DC2626',
    websiteUrl: 'https://rpgcl.gov.bd',
    capacityData: '5.5',
    icon: 'droplet',
    kpiValue: '5.5',
    kpiUnit: 'MMTPA',
    description: 'Liquefied natural gas importer and regasifier',
  },
  {
    id: 'coal-suppliers',
    label: 'Coal Suppliers',
    designation: 'Fuel Supplier',
    category: 'fuel',
    status: 'normal',
    nodeColor: '#DC2626',
    capacityData: '18',
    icon: 'trending',
    kpiValue: '18',
    kpiUnit: 'Million Tonnes/Year',
    description: 'Imported coal from international markets',
  },
  {
    id: 'renewable-fuel',
    label: 'Renewable Energy Sources',
    designation: 'Fuel Supplier',
    category: 'fuel',
    status: 'normal',
    nodeColor: '#DC2626',
    capacityData: '1500',
    icon: 'leaf',
    kpiValue: '1500',
    kpiUnit: 'MW Target',
    description: 'Solar, wind, and biomass resources',
  },
  {
    id: 'pgcb',
    label: 'PGCB (National Grid)',
    designation: 'Transmission Company',
    category: 'transmission',
    status: 'normal',
    nodeColor: '#1E3A8A',
    websiteUrl: 'https://pgcb.net.bd',
    capacityData: '24000',
    icon: 'network',
    kpiValue: '24000',
    kpiUnit: 'Circuit KM',
    description: 'Transmission backbone of Bangladesh power system',
  },
  {
    id: 'nldc',
    label: 'NLDC (National Load Despatch Centre)',
    designation: 'Grid Operations',
    category: 'transmission',
    status: 'normal',
    nodeColor: '#1E3A8A',
    websiteUrl: 'https://pgcb.net.bd/site/page/nldc',
    capacityData: '14000',
    icon: 'cpu',
    kpiValue: '14000',
    kpiUnit: 'MW Real-time',
    description: 'Real-time grid operations and frequency control',
  },
  {
    id: 'dpdc',
    label: 'DPDC (Dhaka South Distribution)',
    designation: 'Distribution Company',
    category: 'distribution',
    status: 'normal',
    nodeColor: '#D97706',
    websiteUrl: 'https://dpdc.org.bd',
    capacityData: '3200',
    icon: 'network',
    kpiValue: '3200',
    kpiUnit: 'MW Peak',
    description: 'Distribution company serving Dhaka south and suburbs',
  },
  {
    id: 'desco',
    label: 'DESCO (Dhaka North Distribution)',
    designation: 'Distribution Company',
    category: 'distribution',
    status: 'normal',
    nodeColor: '#D97706',
    websiteUrl: 'https://desco.org.bd',
    capacityData: '2800',
    icon: 'network',
    kpiValue: '2800',
    kpiUnit: 'MW Peak',
    description: 'Distribution company serving Dhaka north and suburbs',
  },
  {
    id: 'breb',
    label: 'BREB (Rural Electrification Board)',
    designation: 'Distribution Company',
    category: 'distribution',
    status: 'normal',
    nodeColor: '#D97706',
    websiteUrl: 'https://breb.gov.bd',
    capacityData: '1500',
    icon: 'network',
    kpiValue: '1500',
    kpiUnit: 'MW Peak',
    description: '80 Palli Bidyut Samities serving rural areas',
  },
  {
    id: 'nesco',
    label: 'NESCO (North Distribution)',
    designation: 'Distribution Company',
    category: 'distribution',
    status: 'normal',
    nodeColor: '#D97706',
    websiteUrl: 'https://nesco.org.bd',
    capacityData: '1200',
    icon: 'network',
    kpiValue: '1200',
    kpiUnit: 'MW Peak',
    description: 'Distribution company serving northern regions',
  },
  {
    id: 'wzpdc',
    label: 'WZPDC (West/South Distribution)',
    designation: 'Distribution Company',
    category: 'distribution',
    status: 'normal',
    nodeColor: '#D97706',
    websiteUrl: 'https://wzpdc.org.bd',
    capacityData: '1100',
    icon: 'network',
    kpiValue: '1100',
    kpiUnit: 'MW Peak',
    description: 'Distribution company serving western and southern regions',
  },
  {
    id: 'industrial-consumer',
    label: 'Industrial Consumers',
    designation: 'Consumer Segment',
    category: 'consumer',
    status: 'normal',
    nodeColor: '#7C3AED',
    capacityData: '4800',
    icon: 'factory',
    kpiValue: '4800',
    kpiUnit: 'MW Demand',
    description: 'Garments, textile, cement, and manufacturing sectors',
  },
  {
    id: 'commercial-consumer',
    label: 'Commercial Consumers',
    designation: 'Consumer Segment',
    category: 'consumer',
    status: 'normal',
    nodeColor: '#7C3AED',
    capacityData: '2400',
    icon: 'building',
    kpiValue: '2400',
    kpiUnit: 'MW Demand',
    description: 'Retail, offices, hospitals, and service sectors',
  },
  {
    id: 'agricultural-consumer',
    label: 'Agricultural Consumers',
    designation: 'Consumer Segment',
    category: 'consumer',
    status: 'normal',
    nodeColor: '#7C3AED',
    capacityData: '1800',
    icon: 'leaf',
    kpiValue: '1800',
    kpiUnit: 'MW Demand',
    description: 'Irrigation pumps and agricultural processing',
  },
  {
    id: 'residential-consumer',
    label: 'Residential Consumers',
    designation: 'Consumer Segment',
    category: 'consumer',
    status: 'normal',
    nodeColor: '#7C3AED',
    capacityData: '5600',
    icon: 'users',
    kpiValue: '5600',
    kpiUnit: 'MW Demand',
    description: '35+ million household connections',
  },
]

const parentMap: { [key: string]: string } = {
  powerDiv: 'mpemr',
  energyDiv: 'mpemr',
  bpdb: 'powerDiv',
  'bpdb-coal': 'bpdb',
  'bpdb-gas': 'bpdb',
  'bpdb-hydro': 'bpdb',
  'bpdb-renewable': 'bpdb',
  'summit-power': 'powerDiv',
  'united-power': 'powerDiv',
  'confidence-power': 'powerDiv',
  'other-ipps': 'powerDiv',
  'rental-power': 'powerDiv',
  'adani-godda': 'powerDiv',
  'tripura-import': 'powerDiv',
  petrobangla: 'energyDiv',
  rpgcl: 'energyDiv',
  'coal-suppliers': 'energyDiv',
  'renewable-fuel': 'energyDiv',
  pgcb: 'powerDiv',
  nldc: 'pgcb',
  dpdc: 'powerDiv',
  desco: 'powerDiv',
  breb: 'powerDiv',
  nesco: 'powerDiv',
  wzpdc: 'powerDiv',
  'industrial-consumer': 'nldc',
  'commercial-consumer': 'nldc',
  'agricultural-consumer': 'nldc',
  'residential-consumer': 'nldc',
}

async function seedDatabase() {
  console.log('🌱 Starting database seeding via API...\n')

  try {
    // Create all nodes
    for (const node of nodes) {
      const dataToSend = {
        ...node,
        parentId: parentMap[node.id] || null,
      }

      console.log(`Creating node: ${node.label}...`)

      const response = await fetch(`${BASE_URL}/api/nodes`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(dataToSend),
      })

      if (!response.ok) {
        const error = await response.json()
        console.error(`  ❌ Failed: ${error.error}`)
      } else {
        console.log(`  ✅ Created`)
      }
    }

    console.log('\n✅ Database seeding completed!')
    console.log('\n📊 Next steps:')
    console.log('1. Open http://localhost:3000 to see the visualization')
    console.log('2. Go to http://localhost:3000/admin to manage nodes')
    console.log('3. Login with: admin@power.gov.bd / admin123\n')
  } catch (error) {
    console.error('❌ Seeding failed:', error)
    process.exit(1)
  }
}

seedDatabase()
